### ISSUE TITLE
Problems does not contain package  github.com/hyperledger/fabric/common/localmsp

### ISSUE THREAD

**Issue by Huey97** [Deeptiman/offchaindata#1]
Hi，I just wanna use this project, but this problem occured. Really I don't know how to deal with it.
The problem is:
```
go get github.com/hyperledger/fabric/common/localmsp: module 
github.com/hyperledger/fabric@upgrade (v2.1.1+incompatible) found, 
but does not contain package github.com/hyperledger/fabric/common/localmsp
```
I know the reason is that the package `github.com/hyperledger/fabric/common/localmsp` could not to be download, but how can I get the package ?
Thanks.

**Comment by Deeptiman** [comment]
Hi @Huey97, I have fixed the dependency issues. As the current version of this repository runs on the initial version of hyperledger fabric [v1.3.0].  So, please follow the dependency.sh file to download the required modules and compile the application.

https://github.com/Deeptiman/offchaindata/blob/master/dependency.sh

Thanks
